### PR TITLE
Resized assets to have standard icon size

### PR DESCRIPTION
**Pull request by Spyromaniac31**
## Description
Resized the icons in the Start Menu tile and splash screen assets to better match the standard icon size seen across Microsoft apps

Added a drop shadow to the Start Menu and splash screen assets to match the drop shadow in official Microsoft fluent icons.

## Motivation and Context
Helps XCG fit better with other apps on the Start Menu and makes the icon a better size in the Microsoft Store
[App Icon in Store is too small](https://github.com/microsoft/Xaml-Controls-Gallery/issues/473)

## How Has This Been Tested?

Icon scaled to a size that looks consistent next to other Start Menu tiles

## Screenshots (if appropriate):
image
Right is current, middle is proposed. Text will be on the actual one.

## Types of changes

Sort of N/A
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Spyromaniac31** [comment]
The reason there are 7 commits is because I forgot to reference the issue in the commit message and but I also wanted to make sure the final commit showed the actual changes. Sorry about that.

**Comment by chingucoding** [comment]
No problem, happy that created a PR for this. A few infos on GitHub and this repository:

If you add "Fixes #x" to a PR description, it will close the issue with the number x when the PR get's merged. That means you don't have to include it in your commit message.

It's no problem that you created 7 commits, on this and a lot of other repositories, the PR will get squash-merged, that means all commits get squashed into a single one.

If you have any questions, feel free to ask :)

**Comment by stmoy** [comment]
@Spyromanic31 - these look **awesome** :)  Thank you for doing this!

**Comment by Spyromaniac31** [comment]
@chingucoding I appreciate the tip. I'll let you know if I have any other questions.

@stmoy Glad you like them! Can't wait for the next release

**Pull request merged**
