### PR TITLE
Select correct item in navigation upon opening item from search

### LINKED ISSUE #420: Page navigation from search should expand TreeView and select page
**Describe the bug**
When you search for a page like `ItemsRepeater` in the sample app you're taken directly to the page, but you have no idea where that page exists in the navigation tree. It would help with the discovery of similar controls if they page is brought forth as the selected/opened page in the NavigationView.

**Steps to reproduce the bug**
1. Go to Sample App
2. Search for a control in the search box
3. Select a choice to navigate to that page from the dropdown

**Expected behavior**
Page selected in NavigationView.

**Actual behavior**
No indication of which page I'm viewing in hierarchy.

**Screenshots**

image

image

**Version Info**

Gallery version (found on Settings page): 
1.2.15.0

Windows 10 version:
- [x] Insider Build (19624)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

When the users searches an item, we are now searching for the correct NavigationViewItem and setting it as the selected item. Unfortunately, we need to find the corresponding NavigationViewItem to update selection.
## Motivation and Context

Closes #420
## How Has This Been Tested?

Tested manually by trying both display orientations and searching for a control and visiting the page through the search
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by chingucoding** [comment]
Yes unfortunately, a lot of this code is somewhat a workaround. Maybe it is worth discussing on the WinUI repository, if we want to adjust the behavior in that regard? 

Regarding the not scrolling the selecteditem into view, fixing this here would require us to walk the visual tree, and get the scrollviewer ourselfes, which doesn't sound like a good idea.

**Comment by YuliKl** [comment]
Probably a good idea to start a conversation about this in the WinUI repo. XCG serves as a proving ground for our controls and your change is highlighting some issues with the hierarchical navigation implementation. 

I would definitely avoid doing something unnatural like walking the visual tree ;)

**Comment by chingucoding** [comment]
Created https://github.com/microsoft/microsoft-ui-xaml/issues/3015 to discuss whether the NavigationView behavior should change in that regard.

**Comment by chingucoding** [comment]
@YuliKl I've added the BringIntoView call as suggested by @StephenLPeters , and the selected item will now be on screen, regardless if it was previously on screen or not.

**Pull request merged**
