### PR TITLE
Add "Move to new window" contextmenu to windowing tab view items

### LINKED ISSUE #581: Unable to Drag the Tab outside of the window to spawn a new window using keyboard.
**Describe the bug**

**Steps to reproduce the bug**

1. Launch XAML Control Gallery app.
2. Navigate to TabView button and activate it.
3. Navigate to "Click here to launch the sample" button->Activate it->Turn on ProgressRing toggle switch->Try to Drag the tab outside of the window to spawn a new window and Observe. 

**Expected behavior**

User should be able to create new window by dragging a tab. (or) there should be option to user to do this functionality like open a new window by using context menu on the tab etc.

**Actual behavior**

User is unable to create new window.

**Screenshots**

image

**Version Info**

Gallery version (found on Settings page): 1.2.10.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_queries/edit/23669905)

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

This PR adds a context menu that allows users to move TVIs to a new window.
## Motivation and Context

Closes #581
## How Has This Been Tested?

Tested manually.
## Screenshots (if appropriate):
Screenshot of open contextmenu on TabViewItem

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by anawishnoff** [comment]
@chingucoding This looks good. The only issue I see is that when dragging a TVI into a new window, the following icon shows up:
image

I'm not sure if this is configurable, though - did you notice this as well? @ranjeshj do you know if this icon is configurable?

**Comment by chingucoding** [comment]
I also noticed this but I don't think we can easily customize this. Maybe someone else has a good idea though how we can deal with this.

**Comment by anawishnoff** [comment]
@chingucoding I don't think this is changeable as of now. Going to approve, you may need to merge with master again. Thank you!

**Review by anawishnoff — APPROVED** [review]

**Comment by chingucoding** [comment]
Merged with master @anawishnoff

**Pull request merged**
