### PR TITLE
Adding full stop to one of the control descriptions

### PR DESCRIPTION
**Pull request by salmanmkc**
## Description
Was missing a full stop. 

## How Has This Been Tested?
Building the project.

## Screenshots (if appropriate):
Before:
image

After:
image

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by chingucoding** [comment]
I think you accidently added the commit to your branch containing the changes for the scaling issues, instead of fixing the issue in master (and thus only changing the missing full stop in the description, instead of applying the changes from #236 and the missing full stop) 😅

**Comment by YuliKl** [comment]
Adding a period shouldn't require changes to 11 files 🤣

**Comment by salmanmkc** [comment]
> Adding a period shouldn't require changes to 11 files 🤣

yeah I'm sorry, was experimenting with GitHub stuff and thought it worked, but ended up messing up

**Comment by stmoy** [comment]
To fix this, please Fetch/Pull from origin/master, merge from master into your local branch, and push the merge.

Or abandon this PR, re-branch from master, add the period, and resubmit.

**Comment by salmanmkc** [comment]
Resubmitted PR

**Pull request closed without merging**
