### PR TITLE
Switch to latest prerelease

### LINKED ISSUE #440: NavigationView control "API in action" crashes when you enable PaneFooter visible.
**Describe the bug**

NavigationView control "API in action" crashes when you enable PaneFooter visible.

**Steps to reproduce the bug**

1. Go to NavigationView control
2. Scroll down to API in action control and enable PaneFooter

**Expected behavior**

For the setting to enable

**Actual behavior**

Crash

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] May 2020 Update
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Update to latest prerelease to have latest bug fixes in the app.
## Motivation and Context

Keep app up to date and fixes #440 

## How Has This Been Tested?

Running steps in issue #440
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

@ranjeshj The 2.4.2 release still results in the app crashing. Is this intended? It seems that the fix is not in that version which is a bit confusing.

### CODE REVIEW

**Comment by ranjeshj** [comment]
>@ranjeshj The 2.4.2 release still results in the app crashing. Is this intended? It seems that the fix is not in that version which is a bit confusing.

I just checked this morning and it seemed to not crash. Can you verify that you have the correct version of the package ?

**Comment by chingucoding** [comment]
Okay, so it did not work the first time I switched after your comment, purging the complete folder fixed the issue. Does `clean solution` not get rid of the nuget packages? Shouldn't installing a new version  WinUI version handle the necessary logic?

**Comment by ranjeshj** [comment]
> Okay, so it did not work the first time I switched after your comment, purging the complete folder fixed the issue. Does `clean solution` not get rid of the nuget packages? Shouldn't installing a new version WinUI version handle the necessary logic? Both times it reported that it is using version 2.4.2, but only the second time apparently it actually did.

Probably not. I would have expected the nuget restore in the next build/rebuild to have identified the update in version and restored the appropriate version though.

**Comment by chingucoding** [comment]
Closing this as #470 does the same.

**Pull request closed without merging**
