### PR TITLE
New icon!

### LINKED ISSUE #374: [Feature request] Modernizing the XAML Controls Gallery icon
# Summary of the new feature/enhancement

The current XAML Controls Gallery icon is in the MDL2 style. Since WinUI is modernizing the Windows XAML platform, the gallery app icon should reflect this as well. It should be at the front of innovation and reflect the latest changes of the Windows platform. In 2020, we'll see lots of inbox application icons modernized ([more on Microsoft Design's push to re-design hundreds of OS icons here](https://medium.com/microsoft-design/the-ripple-effect-expanding-our-icon-design-system-74b4d916b7a4)).

# Proposed technical implementation details

The proposal is to redesign the current XAML Controls Gallery icon, so it feels part of the Windows 10 family of experiences (e.g. Terminal, other inbox apps)

- While add it, maybe we need to change the (tile) accent color as well so it fits in a bit more with the other icons.

- Would be nice if we can bring the WinUI logo to this app icon as well!
logo

For context, here is the current Xaml Controls Gallery icon: 
image

Windows Community Toolkit Sample App app icon issue: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3182

### PR DESCRIPTION
**Pull request by stmoy**
## Description

Fixes #374 

## How Has This Been Tested?

Built and run locally

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by chingucoding** [comment]
The new icon looks awesome!

However, in start menu, there is still the white monochromatic icon of the app, is that expected?:
image

Also, was there a specific reason to remove the blue background color? Most other MS apps use a hard coded color and not the accent color.

**Comment by mdtauk** [comment]
Not sure the shadowing and shading on the icon's layers - matches the ones used on other Microsoft icons.  Has this design been sent to the Icon design team for their approval?

The design is nice and simple, so makes sense coming from the previous logo. :)

**Comment by salmanmkc** [comment]
Looks great!

**Comment by mdtauk** [comment]
A quick idea of how more Fluent shading and shadows would look on the design.
image

**Comment by stmoy** [comment]
Thanks for the feedback, y'all. 

>However, in start menu, there is still the white monochromatic icon of the app, is that expected?

This is a caching issue and should clear up after a little while. You could also try manually uninstalling the app and reinstalling it. I was seeing this for a little while too, but it seems to have fixed itself this afternoon. 

> Also, was there a specific reason to remove the blue background color? Most other MS apps use a hard coded color and not the accent color.

This was requested by @niels9001 in #374. The blue color of the Gallery didn't have a significant meaning or brand, so that's why I removed it. 

> Has this design been sent to the Icon design team for their approval?

As the owner of the XCG app, I personally think it's the most important app in the world 😉 But since it's just a small sample app written by the WinUI team, the icon folks don't have the bandwidth to review this asset. 

> A quick idea of how more Fluent shading and shadows would look on the design.

Thanks for putting this together - I like the lighting and shadows. However, the design in this PR maintains consistency with @niels9001's original design, so that's the one I'm going with.

**Comment by niels9001** [comment]
@stmoy Looks great :)!!! 

One minor comment: could we increase the blurradius of the background shadow a bit more for the tile images so it fits in a bit more with the other Fluent icons? I think one of the icon designers could help there (Mike was on the Windows Insider podcasts talking about icons, maybe we can reach out to him https://twitter.com/MsyndicateD?)

**Comment by mdtauk** [comment]
> @stmoy Looks great :)!!!
> 
> One minor comment: could we increase the blurradius of the background shadow a bit more for the tile images so it fits in a bit more with the other Fluent icons? I think one of the icon designers could help there (Mike was on the Windows Insider podcasts talking about icons, maybe we can reach out to him https://twitter.com/MsyndicateD?)
> 
> image

This was what I was talking about in my earlier comment.  The icon shadowing and shading does not follow the Fluent icons.  I used the values included in the WinUI Figma design kit.

The gradient of the colour should be from Top Left to Bottom Right.

On Windows the Icons do not include the extra bevelling, however they do on Android and iOS, so that is not a problem.

image

**Comment by stmoy** [comment]
Gotcha, thanks for the help @mdtauk. 

Thoughts on this?

Picture5

I'm still having a bit of trouble with the shadow. The difficulty is that the colors for the icon are very close to the default accent color - the reason I "hardened" the shadow was to help ensure that the icon itself was visible in all the blue. The shadows shown here have been modified from the original submission but I don't want to regenerate all of the assets yet.

**Comment by mdtauk** [comment]
You could increase the contrast if you are worried about the blue's visibility.  But not everyone uses the default Microsoft blue Accent Color.  Eventually of course, the Live Tiles will be using Acrylic, which will help.

HxMailMediumTile scale-400

The lightest blue area is  #50e6ff  top left  -  #29b0ea  bottom right

Medium blue is  #28afea  -  0a86da

Dark blue strip is  #0669bb  -  #0f5195

**Comment by stmoy** [comment]
Third try's a charm? @mdtauk 

icon

**Comment by chingucoding** [comment]
Since the office apps are now using a grey for their background, maybe we should do the same? 🤔

**Comment by mdtauk** [comment]
> Since the office apps are now using a grey for their background, maybe we should do the same? 🤔

In light theme, the grey may be a bit overpowering in its darkness.  I wish the Windows Team would get the Acrylic tiles working ASAP

**Comment by stmoy** [comment]
> Since the office apps are now using a grey for their background, maybe we should do the same?

Yeah, I considered that, but the XCG isn't an Office app. It's more akin to a "widget" app like Calculator or Alarms, which use the user accent color. 

If y'all are good with this, I'm going to go ahead and approve/merge this PR.

**Pull request merged**
