### PR TITLE
Fix incorrect xaml source code in InfoBadgePage.xaml

### PR DESCRIPTION
**Pull request by HO-COOH**
## Description

Self-explanatory

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by chingucoding — APPROVED** [review]
Looks good to me, thank you for fixing this!

**Comment by onein528** [comment]
Linked to #822.

**Comment by onein528** [comment]
mention issue #822

**Review by onein528 — APPROVED** [review]

**Review by onein528 — CHANGES_REQUESTED** [review]
**Broken** xaml source code:
```diff
-&lt;SymbolIcon Symbol="Sync" HorizontalAlignment="Center"InfoBadgeStyle}" /&gt;
+&lt;SymbolIcon Symbol="Sync" HorizontalAlignment="Center" Style={StaticResource InfoBadgeStyle}" /&gt;
```

Line 120

#822

**Review by onein528 — APPROVED** [review]

**Comment by gregwoo-microsoft** [comment]
Looks great! Thank you @HO-COOH for fixing that. I'm approving it now :)

**Review by gregwoo-microsoft — APPROVED** [review]
💯

**Pull request merged**
