### PR TITLE
Progressring updates

### LINKED ISSUE #485: ProgressRing code sample is missing muxc namespace
**Describe the bug**

ProgressRing in a new WinUI control. Because the sample page is showing the WinUI ProgressRing rather than the inbox control, its sample code needs to show the right namespace.

**Steps to reproduce the bug**

1. Go to ProgressRing page
2. Look at sample line of markup.

**Expected behavior**

Sample reads `<muxc:ProgressRing/>`

**Actual behavior**

Sample reads `<ProgressRing/>`

**Screenshots**

image

**Version Info**

Gallery version (found on Settings page): 

1.2.15.0

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Update images, the namespaces used in the sample code and the namespace used in the page code.
## Motivation and Context

Closes #485 
## How Has This Been Tested?

Tested manually
## Screenshots (if appropriate):
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by YuliKl** [comment]
Looks great! One more request - can you add a "New" tag to ProgressRing, just like the AutomationProperties tile has? And probably update ProgressBar's from "Preview" also to "New" while you're in that file. Thank you!

**Comment by stmoy** [comment]
Thank you for making these changes @chingucoding! Double checking - it looks like the black part of the ProgressRing image is fuzzy or something. Is it just me? 

image

**Comment by chingucoding** [comment]
Sure @YuliKl , I'll change that.

@stmoy Strange, now I see it too. I'll (hopefully) fix this soon.

**Comment by chingucoding** [comment]
image

Updated images and controls json file now.

**Comment by stmoy** [comment]
Thanks @chingucoding. I'm still seeing some strange rendering artifacts or something - how are these image files generated?

**Comment by chingucoding** [comment]
I've taken a screenshot of the actual progressring, removed background and scaled them down using GIMP

**Comment by stmoy** [comment]
Perhaps. What does it look like in dark theme? Most (all?) of the icons have a solid white border, I believe. So I think we'll need that here as well.

**Comment by chingucoding** [comment]
It looks bad:

image

Unfortunately, I am definitely not an expert on this area :/

**Comment by stmoy** [comment]
Thanks for checking. I think we'll probably want to hold off taking this change until the images are fixed (or removed from the change). @yulikl do you have thoughts on how to generate one of these icons? Maybe we could ask our friend @mdtauk 😅

**Comment by mdtauk** [comment]
> Thanks for checking. I think we'll probably want to hold off taking this change until the images are fixed (or removed from the change). @YuliKl do you have thoughts on how to generate one of these icons? Maybe we could ask our friend @mdtauk 😅

At such a small size, its going to be a struggle, unless you use transparency for the ring itself.

if you wanted it to all be Opaque, thickness is the only option you can change
image

Or use a dashed line for the track ring

**Comment by chingucoding** [comment]
For dark theme however, we would still need a white border of sorts (similiar to other icons) since otherwise, you wouldn't be able to see that well.

**Comment by stmoy** [comment]
For context, many of the other icons are not square nor mono-colored: 

image

image

**Comment by stmoy** [comment]
@chingucoding, what about this?

ProgressIcon

image

**Comment by chingucoding** [comment]
Those look fine to me. I am a bit concerned how the ring would look like on the NavigationView given that it is being displayed very small, though it would probably be fine.

Would you like to update the images or would you like me to? We would first need to remove the background to make it transparent and blend in well with the other icons.

**Comment by mdtauk** [comment]
image

**Comment by stmoy** [comment]
Thanks @mdtauk - one further clarification: the light and dark theme use the same assets today, meaning we need a single asset that looks good in both themes. 

>  I am a bit concerned how the ring would look like on the NavigationView given that it is being displayed very small, though it would probably be fine.

Oh, you're right. Oops. The NavigationView only uses FontIcons right now to avoid an issue where using custom assets wouldn't render on first launch. I think we should avoid using a custom asset in the NavigationView and change the icon to a different font icon. 

> We would first need to remove the background to make it transparent and blend in well with the other icons.
The first picture I included has a transparent background.

**Comment by mdtauk** [comment]
> Thanks @mdtauk - one further clarification: the light and dark theme use the same assets today, meaning we need a single asset that looks good in both themes.
> 
> > I am a bit concerned how the ring would look like on the NavigationView given that it is being displayed very small, though it would probably be fine.
> 
> Oh, you're right. Oops. The NavigationView only uses FontIcons right now to avoid an issue where using custom assets wouldn't render on first launch. I think we should avoid using a custom asset in the NavigationView and change the icon to a different font icon.
> 
> > We would first need to remove the background to make it transparent and blend in well with the other icons.
> > The first picture I included has a transparent background.

You could separate the Progress Segment from the Ring, and overlay one Glyph on top of the other - so a Font Icon can still be used.  This is what is done for the ink toolbar controls

**Comment by chingucoding** [comment]
> Oh, you're right. Oops. The NavigationView only uses FontIcons right now to avoid an issue where using custom assets wouldn't render on first launch. I think we should avoid using a custom asset in the NavigationView and change the icon to a different font icon.

Ohhhhh, that makes sense. In that case, the question would be, what the new icon would be if we choose to change it. The current item seems like one of the only ones suitable for this use category. We could use 
image but I am not sure if it's that good of a choice here.

**Comment by chingucoding** [comment]
> You could separate the Progress Segment from the Ring, and overlay one Glyph on top of the other - so a Font Icon can still be used. This is what is done for the ink toolbar controls

But are these distinct parts available as font icons? In addition to that, I am not 100% sure if we would be able to load them from the JSON or if we would need to adjust the current "icon" loading process.

**Comment by mdtauk** [comment]
> > You could separate the Progress Segment from the Ring, and overlay one Glyph on top of the other - so a Font Icon can still be used. This is what is done for the ink toolbar controls
> 
> But are these distinct parts available as font icons? In addition to that, I am not 100% sure if we would be able to load them from the JSON or if we would need to adjust the current "icon" loading process.

I just drew those icons ideas in figma - does the gallery just use Segoe MDL2, or a custom font?

**Comment by chingucoding** [comment]
> I just drew those icons ideas in figma - does the gallery just use Segoe MDL2, or a custom font?

In it's current form, we only use the Segoe MDL2 Assets font.

**Comment by mdtauk** [comment]
> > I just drew those icons ideas in figma - does the gallery just use Segoe MDL2, or a custom font?
> 
> In it's current form, we only use the Segoe MDL2 Assets font.

That is gonna become problematic as the pace of updates outstrips that of the font.  Not to mention the new Fluent Icons only available as SVGs for now

**Comment by stmoy** [comment]
> That is gonna become problematic as the pace of updates outstrips that of the font. Not to mention the new Fluent Icons only available as SVGs for now

Agreed, but this is a separate issue from the one that @chingucoding is trying to fix 😅

**Comment by chingucoding** [comment]
Yes, another thing is that we only need a small icon now as the progressring icon is used for one of the categories.
However given that with hierarchical NavigationView, we also show the icons of every control in the NavView now, we should optimize for that too:

image

**Comment by mdtauk** [comment]
> > That is gonna become problematic as the pace of updates outstrips that of the font. Not to mention the new Fluent Icons only available as SVGs for now
> 
> Agreed, but this is a separate issue from the one that @chingucoding is trying to fix 😅

>

> Yes, another thing is that we only need a small icon now as the progressring icon is used for one of the categories.
> However given that with hierarchical NavigationView, we also show the icons of every control in the NavView now, we should optimize for that too:
> 
> image

Sure.  It would also be good to synchronise the icons used in the controls gallery, with the icons used in Visual Studio for the SDK - and so more flexibility with icon formatting (multiple colours) would be ideal

**Comment by stmoy** [comment]
@chingucoding - what about U+E8F2 for the NavigationView icon? 

image

**Comment by chingucoding** [comment]
Good idea! I've switched it out. What icon should we use for the ProgressRing?

**Comment by stmoy** [comment]
Does this one work?

ProgressIcon

**Comment by chingucoding** [comment]
Hmm, the edges look a bit weird:

image

**Comment by stmoy** [comment]
Hrm, weird. That does look bad. I'll see if I can fix it in a little bit, but we might need some help. 

@mdtauk, can you help out? The requirements are: 

- one asset for both light and dark theme
- does not need to be (and probably shouldn't be) square
- 72 x 72 px

**Comment by mdtauk** [comment]
> Hrm, weird. That does look bad. I'll see if I can fix it in a little bit, but we might need some help.
> 
> @mdtauk, can you help out? The requirements are:
> 
> * one asset for both light and dark theme
> * does not need to be (and probably shouldn't be) square
> * 72 x 72 px

72 x 72 doesn't scale neatly to 16 x 16 for the Navigation view - but it does for 12px and 24px icons.  For them to work at small sizes, the template may need to change, and that doesn't give a lot of resolution if the icons are going to use borders to enable Light and Dark use.

Is there no scope for providing Light and Dark assets?

**Comment by chingucoding** [comment]
I don't think 72 x 72 is a hard limit here right @stmoy? If its easier to scale to small sizes, I think another size would be fine too. But I'll let Steven comment on that.

Regarding Light/Dark assets, I am not sure when we will do this, as this would require definitely more work on the loading of the "data json".

**Comment by stmoy** [comment]
Rewinding a little bit. We have two assets that we need to update - each of them has their own requirements as they exist in the app right now.

- Tile Icon
  - one asset for both light and dark theme
  - does not need to be (and probably shouldn't be) square
  - 72 x 72 px (though not a *hard* requirement)

- NavigationView **Group** Icon ("Status and Info")
  - A single font glyph pulled from MDL2 font 

- NavigationView **ProgressRing** Icon
  - Will get scaled down from the tile asset

For the "Status and Info" icon, we need to use an existing font glyph in the MDL2 asset font for right now. Although the NavView technically supports custom asset icons, there is an unresolved bug where the icon doesn't render on first launch that we'd need to investigate/fix before putting in a custom asset. This is beyond the scope of the current PR.

For the Tile icon, we need a single asset that works in both light and dark theme. The asset will be scaled to 72x72 as this is the size of all of our other assets. Although the asset could technically be a different size, it will always get scaled to 72x72, meaning we should probably provide something at this scale if possible. We can investigate having different assets for light and dark theme, but this would also be beyond the scope of the current PR. 

For the ProgressRing icon within the hierarchical NavigationView, it naively uses a scaled version of the Tile icon. Although it might not be optimal, that's what every other control page does as well.

**Comment by mdtauk** [comment]
@stmoy  I have started making some 72 x 72 icons, that should scale down to 24x24 and 12x12
image

**Comment by stmoy** [comment]
Thanks @mdtauk for providing these assets. They look nice! The complete set of assets we'd need to update if we wanted to do a visual refresh for all of the tiles are located here: https://github.com/microsoft/Xaml-Controls-Gallery/tree/master/XamlControlsGallery/Assets

I'm hoping to unblock this PR specifically by providing a targeted asset to replace the Progress Ring one. @chingucoding, is this one any better? I took the RadioButton asset and modified it, so hopefully it's close 🤞

ProgressIconSmall4

**Comment by chingucoding** [comment]
Definitely looks better, but the roundedness is very problematic here I think:

image

Unfortunately, there isn't much we can do about this, progressring is a circle. Maybe if we chose wider circles for the border and the "control"?

**Comment by stmoy** [comment]
Agreed, this one looks better but doesn't quite feel right yet... Bleh. I think you're right that thicker borders will probably look better. 

How's this?

ProgressIconSmall7

**Comment by chingucoding** [comment]
This looks fine to me:

image

**Comment by stmoy** [comment]
:shipit: 

Thank you for the help and iteration, @chingucoding! Double checking - how does it look in light mode?

I'd still love to take a holistic pass as @mdtauk mentions, but this seems fine to me for now.

**Comment by chingucoding** [comment]
Light mode also looks good in my opinion:

image

**Comment by chingucoding** [comment]
Pushed the image, thanks for providing the new images @stmoy and thank you for your efforts and help @mdtauk .

The new icons you showed @mdtauk look great! If you want we can update them holistically in a separate PR if @stmoy is fine with that.

**Comment by stmoy** [comment]
@chingucoding - is ProgressIcon used anymore? If not, can it be removed?

**Comment by chingucoding** [comment]
> @chingucoding - is ProgressIcon used anymore? If not, can it be removed?

I can't find any "ProgressIcon" in the XCG code 😅

**Comment by stmoy** [comment]
It's one of the files included in the changelist. https://github.com/microsoft/Xaml-Controls-Gallery/pull/489/files#diff-478ec5ba36eaedd60dc7b04727c64127

**Comment by chingucoding** [comment]
Ohhh right, yes that's not needed anymore. Removed it. Totally forgot that.

**Comment by chingucoding** [comment]
Haha love it, thank you @stmoy !

**Comment by mdtauk** [comment]
I made a somewhat related issue post some time ago in the WinUI repo, but when I am done with the initial set of icons, I guess I can make a new issue here for it.

https://github.com/microsoft/microsoft-ui-xaml/issues/1204

**Comment by chingucoding** [comment]
Those new items look awesome! Would you like me to create a tracking issue in this repo to update them once you are finished and happy with the new icons?

**Comment by mdtauk** [comment]
> Those new items look awesome! Would you like me to create a tracking issue in this repo to update them once you are finished and happy with the new icons?

Hold off until I have a complete set - I may have to do simplified 16px versions as the scaling just does not play nice - but the 72, 48, 24 should work find with these vector shapes.

**Comment by mdtauk** [comment]
Ok so I think this is everything included in the Gallery's assets.  I am posting it here - each icon at 72x72 and 16x16 size - and they should work on Light and Dark backgrounds.

@chingucoding  @stmoy  @YuliKl 

Any which stand out as odd or wrong, or any feedback in particular would be welcome, before making a separate proposal.

All New Fluent WinUI Gallery Icons

**Comment by chingucoding** [comment]
Can you add labels for the icons, that is what icon would correspond to which control? Also I am not sure if the color palette would be the best image for RadioalGradientBrush. Another question, was there a specific reason for going more dark themed icons?

Beside that, those new icons look really good!

**Comment by mdtauk** [comment]
> Can you add labels for the icons, that is what icon would correspond to which control? Also I am not sure if the color palette would be the best image for RadioalGradientBrush. Another question, was there a specific reason for going more dark themed icons?
> 
> Beside that, those new icons look really good!

I was trying to find an approach that worked equally well for Light and Dark themes - these read well on both to me, but all of it is changeable of course.

Here is the Figma file with the icons in.  They are in Frames with names on.  I used the Treeview from the Gallery app to sort them.  The RadialGradientBrush is in the motion section for whatever reason - I think it should probably go into Styles however.

[Shared WinUI Gallery Icons.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/4908454/Shared.WinUI.Gallery.Icons.zip)

**Comment by chingucoding** [comment]
Oh yes, RadialGradientBrush is in the style section now, but not in the store version yet I think.
I think light themed icons are more "friendly" and more "inviting", but that's just my opinion.

**Comment by mdtauk** [comment]
> Oh yes, RadialGradientBrush is in the style section now, but not in the store version yet I think.
> I think light themed icons are more "friendly" and more "inviting", but that's just my opinion.

Here are the icons with the colours inverted.
All New Fluent WinUI Gallery Icons - Inverted

**Comment by chingucoding** [comment]
Those look awesome! Thank you for helping and making those.

**Comment by mdtauk** [comment]
I fixed the Gradient Icon, and added the Figma with the inverted colours

**Comment by mdtauk** [comment]
Labels Added
All New Fluent WinUI Gallery Icons - Inverted
[Shared WinUI Gallery Icons Inverted.zip](https://github.com/microsoft/Xaml-Controls-Gallery/files/4909526/Shared.WinUI.Gallery.Icons.Inverted.zip)

**Comment by chingucoding** [comment]
Thank you for the updated version with labels. Regarding your dark theme concern, this is how it looks like with a dark background:

image

**Comment by mdtauk** [comment]
> Thank you for the updated version with labels. Regarding your dark theme concern, this is how it looks like with a dark background:
> 
> image

At a first glance it appears fine, but after long periods?

I know this is part of the reason colours are reduced with Dark Mode UI.

I could be overthinking it perhaps?

**Comment by chingucoding** [comment]
> At a first glance it appears fine, but after long periods?
>
> I know this is part of the reason colours are reduced with Dark Mode UI.
>
> I could be overthinking it perhaps?

That's a good point. I don't think that you are overthinking this, it is definitely a valid concern. Currently the icons have around the same brightness:

image

I suppose it was fine back then, so it is now? I never felt that the icons are too bright over time, especially since you actually don't spend too much time with them. Generally you search for a page and visit said page, and are looking to much at those control "overviews".

**Comment by mdtauk** [comment]
Eitherway, I think the icons work both inverted and un-inverted, so they are out there now if the community and the Repo owners want them.

It would be nice if the Visual Studio toolbox synced with a single set of icons, but that is a much bigger ask 😛

The figma file is there too if tweaks are needed, so I will await comments,

**Comment by stmoy** [comment]
Thanks for including this, @mdtauk!

I think we'd want to update both the WinUI icons and the Xaml Controls Gallery icons at the same time. CC: @ranjeshj - thoughts on cost to do this?

I think the next steps would be to file one more issue on the XCG repo saying "update the icons alongside https://github.com/microsoft/microsoft-ui-xaml/issues/1204", and include a link to all of the image assets. I think two issues are appropriate and they should probably be done at around the same time. 

CC: @chigy for visibility as well

**Comment by mdtauk** [comment]
@stmoy  Do you need me to make an issue for this, or is that something you will be doing?

**Comment by stmoy** [comment]
Filed: https://github.com/microsoft/Xaml-Controls-Gallery/issues/504

**Pull request merged**
