### PR TITLE
CalendarPage.xaml alignment fixed

### PR DESCRIPTION
**Pull request by salmanmkc**
## Description
Set the vertical alignments of the RadioButtons and CheckBoxes on CalendarPage.xaml 

## Motivation and Context
Alignment can be off with scaling
https://github.com/microsoft/microsoft-ui-xaml/issues/1520

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by stmoy** [comment]
In the future, these sorts of similarly related topic PRs can be consolidated into a single PR.

**Comment by salmanmkc** [comment]
> In the future, these sorts of similarly related topic PRs can be consolidated into a single PR.

yeah, sorry, the PR that I closed had them all in one, but I thought it was messy and it had some issues so I just ended up redoing them like this, was told that more PRs are better to assign but have also been told since that similar ones should be combined. Am making a big PR with similar changes all in one currently.

**Comment by YuliKl** [comment]
And also this won't fix the underlying issue.

**Comment by YuliKl** [comment]
This change does not address the underlying problem.

**Pull request closed without merging**
