### PR TITLE
Fixed descriptions and subtitles

### PR DESCRIPTION
**Pull request by salmanmkc**
## Description
All the subtitles and descriptions now fit, most of them I just needed to swap

## Motivation and Context
To the viewer, you would have a lot of descriptions of each control that do not fit in the view, so I decided to fix them.

## How Has This Been Tested?
Building the project and testing different sizes. To see all you can go to the All Controls tab.

## Screenshots (if appropriate):
**Before:**
image
image
image
image
image

_______________________________________________________________________________________________________

**After:**
image
image
image

image
image

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by YuliKl** [comment]
@salmanmkc, there's something strange about your fork of the xaml-controls-gallery repo. I'm not able to build your version of the project, and the file structure is not right. 

I'm going to take a loser look at the file changes in the PR, but for future work maybe start over with a new fork?

**Comment by salmanmkc** [comment]
Pretty sure this was a new fork made either yesterday or today, could it be the master merge I just did?

**Comment by stmoy** [comment]
Thank you for contributing, Salman! Rather than changing all of the text strings to swap Subtitle and Description, we can tell the tile to display the Subtitle instead of the Description. In ItemTemplates.xaml [(link to exact line)](https://github.com/microsoft/Xaml-Controls-Gallery/blob/7035fb8c3bd140b73993ce6b9fa6fb07f114f123/XamlControlsGallery/ItemTemplates.xaml#L61) you can see that the Text is being bound to Description. If you swap that out with Subtitle, does that fix the issue?
 
We want to ensure that the meaning behind the text for the Subtitle and the Description remains semantically consistent. Swapping the literal text strings also swaps the meaning, which also surfaces in other parts of the app (namely at the top of each sample page). We should try to isolate the change as much as possible, meaning the correct fix would be to just change the text displayed rather than the text itself. I know you did a bunch of work to swap the text, but this change isn’t the correct way to solve this issue.
 
The fastest thing to do at this point would probably be to abandon the PR and submit it with this one-line change. 
 
Again: thank you for looking into this issue – we agree that the AFTER screenshots look way better when all the text is shown!

**Comment by salmanmkc** [comment]
Cool, yeah thought of that midway changing everything, and I was like, oh well, it's too late haha

**Comment by salmanmkc** [comment]
was like 3am again and I was tired, forgive me for my silly method

**Comment by stmoy** [comment]
No worries at all - it happens to all of us. Thank you again for taking the time to help make the XCG better!

**Comment by salmanmkc** [comment]
> No worries at all - it happens to all of us. Thank you again for taking the time to help make the XCG better!

No worries, I'm trying to get better, hope to make more substantial changes in the future! These commits should have fixed it.

**Comment by salmanmkc** [comment]
Some changes I forgot to show in the description:
Before:
image

After:
image

**Pull request merged**
