### PR TITLE
Animated visual player page: Scaling fixes

### PR DESCRIPTION
**Pull request by salmanmkc**
Doesn't scale well on 125 or 175%

## Description
Modified values to scale well

## Motivation and Context
Better scaling for values

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by stmoy** [comment]
Oops, it looks like this PR slipped my radar and lived in limbo for a long time. Now it has conflicts with the main branch. @salmanmkc - can you resolve these issues?

**Comment by Poopooracoocoo** [comment]
@salmanmkc pingy ping pong

**Comment by chingucoding** [comment]
@stmoy Should we close this PR now given that it contained unaddressed changes for over 6 months now? Same for #315.

**Comment by stmoy** [comment]
Time sure flies 😅 - the work needed to address the branch conflicts is likely not greater than the value of the change itself, so I am inclined to agree on closing this. @salmanmkc - feel free to submit a new PR if you find the time!

**Pull request closed without merging**
