### PR TITLE
Add vertical flip view example.

### LINKED ISSUE #511: Doc Alignment: Vertical FlipView sample
**Describe the bug**

Add a vertical FlipView sample. 

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/flipview#examples

### PR DESCRIPTION
**Pull request by Chips1234**
# Description
Update the flip view page to include a vertical example.

## Motivation and Context
Closes #511  

## How Has This Been Tested?
Manual tests

## Screenshots (if appropriate):
vertical flip view

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Chips1234** [comment]
Okay

________________________________

**Comment by chingucoding** [comment]
Another thing we could do is have a single sample which let's people change the orientation, like other controls such as NavigationView or SplitView do.

**Comment by Chips1234** [comment]
Yes, that is also feasible

________________________________

**Comment by YuliKl** [comment]
> Another thing we could do is have a single sample which let's people change the orientation, like other controls such as NavigationView or SplitView do.

I like that much better than changing the images.

**Pull request merged**
