### PR TITLE
Fix issue with text not wrapping on AutomationProperties page

### LINKED ISSUE #330: Description on AutomationProperties page should wrap
**Describe the bug**

**Steps to reproduce the bug**

Pre-requisite: 
* Settings--> Ease of Access-->Display-->Drag the Display slider  to  200%-->Apply

Repro steps :
1. Launch XAML Controls Gallery.
2. Activate Automation Properties from home page and observe the text under the header "Automation properties"  is not visible.

**Expected behavior**

Information under the header "Automation properties" should be clearly visible in 200% text scaling.

**Actual behavior**

 Information under the header "Automation properties" gets clipped in 200% text scaling

**Screenshots**

image

**Version Info**

Gallery version (found on Settings page): 

1.2.12.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_queries/edit/24662087)

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Put text in the "Text" property of TextBlock for performance, and add text wrapping.
## Motivation and Context

Fixes #330 
## Screenshots (if appropriate):

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by stmoy** [comment]
> Put text in the "Text" property of TextBlock for performance

What is the performance improvement? I would have expected both ways to be equivalent in terms of performance.

**Comment by chingucoding** [comment]
> > Put text in the "Text" property of TextBlock for performance
> 
> What is the performance improvement? I would have expected both ways to be equivalent in terms of performance.

Though the impact might be rather small performance wise, because we use the `Text` attribute, we can use "fast path" text rendering:

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-block#performance-considerations

**Comment by stmoy** [comment]
> > > Put text in the "Text" property of TextBlock for performance
> > 
> > 
> > What is the performance improvement? I would have expected both ways to be equivalent in terms of performance.
> 
> Though the impact might be rather small performance wise, because we use the `Text` attribute, we can use "fast path" text rendering:
> 
> https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/text-block#performance-considerations

TIL! Thanks for teaching me something today! 🤗

**Comment by chingucoding** [comment]
> Thanks for teaching me something today! 🤗

Happy that I could teach you something 🤗

**Pull request merged**
