### PR TITLE
Remove dead code in settingspage class

### LINKED ISSUE #866: An object created for no reason
Hello, in the SettingsPage.xaml.cs class of[ line 80](https://github.com/microsoft/Xaml-Controls-Gallery/blob/dfa35dc5a25b5c3262b544f9d4117743e4934059/XamlControlsGallery/SettingsPage.xaml.cs#L80), an object was created from the ApplicationViewTitleBar that was not used anywhere in the project. What is the reason?

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

This PR removes some dead inside the SettingsPage class.
## Motivation and Context

Closes #866 
## How Has This Been Tested?

Ran the app manually.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by gregwoo-microsoft** [comment]
@chingucoding I remove an additional function that wasn't used. Let me know what you think

**Comment by chingucoding** [comment]
I think that the function you removed was actually used, it seems that the settings page header is not working anymore.

**Comment by gregwoo-microsoft** [comment]
Ok my bad. I didn't see any references to it but I'll put it back.

**Comment by chingucoding** [comment]
The OnNavigatedTo is one of the special functions that are being called by the XAML Framework itsself, that's why you won't find a reference to it in the XCG code base.

**Review by gregwoo-microsoft — APPROVED** [review]

**Comment by gregwoo-microsoft** [comment]
Awesome! Thank you @chingucoding!

**Pull request merged**
