### PR TITLE
Changing some values so scaling works better

### PR DESCRIPTION
**Pull request by salmanmkc**
Just a few small value changes so that scaling works better, 66 * 1.25 != Z where Z is an integer value, same for 345 * 1.25
## Description
When you use scaling of 125% these values will not be whole numbers.

## Motivation and Context
Post about some alignment issues, couldn't replicate the issue though but changed some values that will end up rounding and added vertical alignment to the checkboxes and radiocontrols. https://github.com/microsoft/microsoft-ui-xaml/issues/1520

## How Has This Been Tested?
Tested to see if much changes, looks the same which is good.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by salmanmkc** [comment]
I now realise I should have deleted the fork and reforked because it has a PR that was merged yesterday, sorry! Is there another way to do that?

**Comment by chingucoding** [comment]
> I now realise I should have deleted the fork and reforked because it has a PR that was merged yesterday, sorry! Is there another way to do that?

I think the following link might be useful:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

**Comment by salmanmkc** [comment]
> > I now realise I should have deleted the fork and reforked because it has a PR that was merged yesterday, sorry! Is there another way to do that?
> 
> I think the following link might be useful:
> 
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

cheers, I've just been managing my fork from the GitHub page, I pulled from the main repo before,  is there something I'm missing?

**Comment by michael-hawker** [comment]
🦙 @salmanmkc for future reference when reviewing, it can be handy to have screenshots of the before and after cases of one of the pages too!

**Comment by salmanmkc** [comment]
> 🦙 @salmanmkc for future reference when reviewing, it can be handy to have screenshots of the before and after cases of one of the pages too!

Yeah, I mentioned that I couldn't replicate the issue, screenshotting wouldn't have shown much or any difference for the ComboBox/RadioButtons, and wouldn't really be visible for the small value changes

**Comment by chingucoding** [comment]
> > > I now realise I should have deleted the fork and reforked because it has a PR that was merged yesterday, sorry! Is there another way to do that?
> > 
> > 
> > I think the following link might be useful:
> > https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork
> 
> cheers, I've just been managing my fork from the GitHub page, I pulled from the main repo before, is there something I'm missing?

I am not quite sure if one would be able to merge branches just using the GitHub page. 😅

However merging branches is something Visual Studio is capable of, so you could use that or merge  in the command line.

**Comment by salmanmkc** [comment]
split into multiple PRs

**Pull request closed without merging**
